# Generated by Django 4.2.2 on 2023-07-04 03:56

import Translator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=Translator.models.get_upload_path),
        ),
    ]
